spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL57Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/zero
    username: root
    password: Legend2001
  mail:
    host: smtp.gmail.com
    port: 587
    username: your Email
    password: Email password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
logging.level.org.springframework: info
